GET /setup HTTP/1.1
Host: localhost:3000

###
GET /brands HTTP/1.1
Host: localhost:3000

###
GET /sneakers HTTP/1.1
Host: localhost:3000

###
GET /occasions HTTP/1.1
Host: localhost:3000

###
POST /sneakers HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "name": "Pursuit",
  "price": 37.8,
  "stock": 500,
  "brand": {
    "brandId": "62334349301e056f50c7fcc0",
    "name": "SCOTT"
  },
  "occasions": [
    {
      "occasionId": "62334349301e056f50c7fcc1",
      "description": "Sports"
    },
    {
      "occasionId": "62334349301e056f50c7fcc2",
      "description": "Casual"
    }
  ]
}