GET http://localhost:3000/brands HTTP/1.1
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.body.length === 3, "Response length is not 3");
});%}

###
GET http://localhost:3000/brands?country=germany HTTP/1.1
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.body.length === 2, "Response length is not 2");
});%}

###
GET http://localhost:3000/brands/1 HTTP/1.1
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.body.name === "Volkswagen", "Response was not Volkswagen");
});%}

###
POST http://localhost:3000/brands HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "Lada",
  "country": "Russia",
  "logo": "https://logos-world.net/wp-content/uploads/2021/09/Lada-Logo.png"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
  client.assert(response.body.name === "Lada", "Response was not Lada");
});%}

###
POST http://localhost:3000/brands HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "blouuu",
  "country": "a",
  "logo": "this is not a link boop"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});%}

###
GET http://localhost:3000/cars HTTP/1.1
Content-Type: application/json
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});%}

###
GET http://localhost:3000/cars?country=england HTTP/1.1
Content-Type: application/json
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.body[0].name ==="720S" , "720S not present");
});%}

###
GET http://localhost:3000/brands/1/cars HTTP/1.1
Content-Type: application/json
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.body.length === 2, "car length not 2");
});%}

###
GET http://localhost:3000/cars/0 HTTP/1.1
Content-Type: application/json
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.body.name === 'Golf', "car found is not golf");
});%}